version: '3.9'


networks:
  default:
    name: 'giga'


volumes:
  giga-logs: 
  giga-prom:
  giga-grafana:


services:
  opensearch:
    container_name: "giga-os"
    image: 'opensearchproject/opensearch:2'
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: 'single-node'
      plugins.security.disabled: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'admin123!ZGT5'
    volumes:
      - giga-logs:/usr/share/opensearch/data

  opensearch-dashboards:
    container_name: "giga-osd"
    image: 'opensearchproject/opensearch-dashboards:2'
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://giga-os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch
  prometheus:
    container_name: "giga-prom"
    image: 'prom/prometheus:latest'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - giga-prom:/prometheus
  grafana:
   container_name: 'giga-grafana'
   image: 'grafana/grafana'
   restart: unless-stopped
   environment:
     GF_INSTALL_PLUGGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
   volumes:
     - giga-grafana:/var/lib/grafana
   ports:
     - '3000:3000'
   depends_on:
     - prometheus
      
