global:
  scrape_interval: 10s
  scrape_timeout: 3s

scrape_configs:
  - job_name: giga-scrape
    static_configs:
      - targets:
          - host.docker.internal:5125      
        labels:
          app: 'giga'